default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: make-format-gitrekt-cli
        name: make format-gitrekt-cli
        entry: make format-gitrekt-cli
        language: system
        pass_filenames: false
      - id: make-check-gitrekt-cli
        name: make check-gitrekt-cli
        entry: make check-gitrekt-cli
        language: system
        pass_filenames: false
