[project]
name = "Gitrekt-cli-wire-messages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "Gitrekt-cli",
    "rich",
]

[tool.uv.sources]
Gitrekt-cli = { path = "../../" }
